### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-filter-json#1]
it look related to the java_integration, need more investigation.
```
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :elasticsearch=>true, :broken=>true, :export_cypher=>true}
FF.F

Failures:

  1) LogStash::Filters::Json parse message into the event "{ "hello": "world", "list": [ 1, 2, 3 ], "hash": { ..." when processed
     Failure/Error: Unable to find matching line from backtrace
     Insist::Failure:
       Expected [1, 2, 3], but got #<Java::JavaUtil::ArrayList:0x41685d91>
     # ./lib/logstash/runner.rb:58:in `run'
     # ./lib/logstash/runner.rb:113:in `run'
     # ./lib/logstash/runner.rb:171:in `run'

  2) LogStash::Filters::Json parse message into a target field "{ "hello": "world", "list": [ 1, 2, 3 ], "hash": { ..." when processed
     Failure/Error: Unable to find matching line from backtrace
     Insist::Failure:
       Expected [1, 2, 3], but got #<Java::JavaUtil::ArrayList:0x4fbfe01c>
     # ./lib/logstash/runner.rb:58:in `run'
     # ./lib/logstash/runner.rb:113:in `run'
     # ./lib/logstash/runner.rb:171:in `run'

  3) LogStash::Filters::Json fixing @timestamp (#pull 733) "{ "@timestamp": "2013-10-19T00:14:32.996Z" }" when processed
     Failure/Error: Unable to find matching line from backtrace
     Insist::Failure:
       LogStash::Timestamp is not a Time
     # ./lib/logstash/runner.rb:58:in `run'
     # ./lib/logstash/runner.rb:113:in `run'
     # ./lib/logstash/runner.rb:171:in `run'

Finished in 0.308 seconds
4 examples, 3 failures

**Comment by talevy** [comment]
this is what I am seeing now. was this an old version that you saw that error in?
```
~/Code/es/talevy-logstash-filter-json (master)$ bundle exec rspec
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :broken=>true, :export_cypher=>true, :integration=>true}
.....

Finished in 0.201 seconds
5 examples, 0 failures

Randomized with seed 48924
```

**Comment by ph** [comment]
possible it's from November 5 and I think @colin work on that part. :)
